### ISSUE TITLE
Google Play Launch Report Crash

### ISSUE THREAD

**Issue by AntHillOracle** [marcojak/MauiMTAdmob#68]
I submitted an internal test build to Google Play and their Pre-launch report lists a crash on 1 device of 8:
Google Pixel 5 64-bit only (redfin_64) - Android 14, crash at: Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0)

Exception android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
   at Plugin.MauiMTAdmob.Platforms.Android.MTAdViewHandler.LoadAd()
   at Plugin.MauiMTAdmob.Platforms.Android.MTAdViewHandler.Current_OnMobileAdsInitialized(Object sender, EventArgs e)
   at Plugin.MauiMTAdmob.MauiMTAdmob.MOnMobileAdsInitialized()
   at Plugin.MauiMTAdmob.MauiMTAdmob.OnInitializationComplete(IInitializationStatus )
   at Android.Gms.Ads.Initialization.IOnInitializationCompleteListenerInvoker.n_OnInitializationComplete_Lcom_google_android_gms_ads_initialization_InitializationStatus_(IntPtr jnienv, IntPtr native__this, IntPtr native_p0)
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0)
  at crc6424817b6e85a95e78.MauiMTAdmob.n_onInitializationComplete (MauiMTAdmob.java)
  at crc6424817b6e85a95e78.MauiMTAdmob.onInitializationComplete (MauiMTAdmob.java:31)
  at com.google.android.gms.ads.internal.client.zzei.zzb (com.google.android.gms:play-services-ads-lite@@22.3.0:8)
  at com.google.android.gms.internal.ads.zzbkl.zzbE (com.google.android.gms:play-services-ads-lite@@22.3.0:3)
  at com.google.android.gms.internal.ads.zzatr.onTransact (com.google.android.gms:play-services-ads-base@@22.3.0:3)
  at android.os.Binder.transact (Binder.java:1183)
  at m.ajj.ba (:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:8)
  at com.google.android.gms.ads.internal.initialization.f.e (:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:9)
  at com.google.android.gms.ads.nonagon.initialization.f.run (:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:9)
  at android.os.Handler.handleCallback (Handler.java:958)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at m.awy.a (:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:1)
  at com.google.android.gms.ads.internal.util.f.a (:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:2)
  at m.awy.dispatchMessage (:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:1)
  at android.os.Looper.loopOnce (Looper.java:205)
  at android.os.Looper.loop (Looper.java:294)
  at android.app.ActivityThread.main (ActivityThread.java:8177)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:552)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:971)

This is Plugin.MauiMTAdmob version 1.3.1.
I have not personally experienced a crash in MTAdMob, but perhaps this stack trace can help you identify something that can benefit from a null check.

**Comment by marcojak** [comment]
Thank you very much  for the report.

I'll have a look at it and release an update to fix the issue.

**Comment by marcojak** [comment]
Fixed. It will be part of the version 1.3.2
